tableextension 80005 "HL Vendor Ext" extends Vendor
{
    fields
    {
        field(80000; "Sales E-Mail"; text[80])
        {}
        field(80001; "Operations E-Mail"; text[80])
        {}
/*        field(80002; "Marketing Rebate Total"; Decimal)
        {}
        field(80003; "Supply Chain Rebate Total"; Decimal)
        {}
         field(80005; "Volume Rebate Total"; Decimal)
        {
        }
*/        
    }
}